site_name: investor
site_description: "investor data science project to develop strategies, algorithms and models"
site_author: "mengwangk"

repo_url: https://github.com/mengwangk/investor
edit_uri: https://github.com/mengwangk/investor/tree/master/docs
docs_dir: "docs"
site_dir: "_docs"

nav:
  - Home: index.md

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - Bash
    - R
    - Dockerfile
    - Python

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.superfences
  - codehilite:
      linenums: true
  - toc:
      permalink: []
      toc_depth: 2

plugins:
  - search