site_name: "Documentation: {{ cookiecutter.package_name }}"
site_description: "Initial documentation"
site_author: "{{ cookiecutter.author_name }}"

edit_uri: ""

docs_dir: "."
site_dir: "../_docs"

use_directory_urls: false

nav:
  - Home: index.md

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - Bash
    - Dockerfile
    - Python

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - def_list
  - codehilite:
      linenums: true

plugins:
  - search